<h1>IDOLA BAGI UMMAT ISLAM</h1>

<p>Muḥammad[10] (bahasa Arab: محمد; lahir di Mekkah, 570 M – meninggal di Madinah, 8 Juni 632 M)[11] adalah seorang nabi dan rasul terakhir bagi umat Muslim.[12] Muhammad memulai penyebaran ajaran Islam untuk seluruh umat manusia dan mewariskan pemerintahan tunggal Islam. Muhammad sama-sama menegakkan ajaran tauhid untuk mengesakan Allah sebagaimana yang dibawa nabi dan rasul sebelumnya.[13]

Lahir pada tahun 570 M di Mekkah, Muhammad melewati masa kecil sebagai yatim piatu. Muhammad dibesarkan di bawah asuhan kakeknya Abdul Muthalib kemudian pamannya Abu Thalib. Beranjak remaja, Muhammad bekerja sebagai pedagang. Muhammad kadang-kadang mengasingkan diri ke gua sebuah bukit hingga bermalam-malam untuk merenung dan berdoa. Diriwayatkan dalam usia ke-40, Muhammad didatangi Malaikat Jibril dan menerima wahyu pertama dari Allah.[14] Tiga tahun setelah wahyu pertama, Muhammad mulai berdakwah secara terbuka,[15] menyatakan keesaan Allah dalam bentuk penyerahan diri melalui Islam sebagai agama yang benar dan meninggalkan sesembahan selain Allah. Muhammad menerima wahyu berangsur-angsur hingga kematiannya.[16] Praktik atau amalan Muhammad diriwayatkan dalam hadits, dirujuk oleh umat Islam sebagai sumber hukum Islam bersama Al-Quran.

Muhammad bersama pengikut awal mendapati berbagai bentuk perlawanan dan penyiksaan dari beberapa suku Mekkah. Seiring penganiayaan yang terus berlanjut, Muhammad membenarkan beberapa pengikutnya hijrah ke Habsyah, sebelum Muhammad memulai misi hijrah ke Madinah pada tahun 622. Peristiwa hijrah menandai awal penanggalan Kalender Hijriah dalam Islam. Di Madinah, Muhammad menyatukan suku-suku di bawah Piagam Madinah. Setelah delapan tahun bertahan atas serangan suku-suku Mekkah, Muhammad mengumpulkan 10.000 Muslim untuk mengepung Mekkah. Serangan tidak mendapat perlawanan berarti dan Muhammad mengambil alih kota dengan sedikit pertumpahan darah. Ia menghancurkan berhala-hala. Pada tahun 632, beberapa bulan setelah kembali ke Madinah usai menjalani Haji Wada, Muhammad jatuh sakit dan wafat. Muhammad meninggalkan Semenanjung Arab yang telah bersatu dalam pemerintahan tunggal Islam dan sebagian besar telah menerima Islam.</p>

<h2>RIWAYAT</h1>

<p>Para ulama dan penulis sirah sepakat bahwa hari kelahiran Muhammad jatuh pada bulan Rabiul Awal.[24] Muhammad lahir di Mekkah, kota bagian selatan Jazirah Arab, sekitar tahun 570, berdekatan dengan Tahun Gajah yang merupakan tahun kegagalan penyerangan Mekkah oleh pasukan bergajah di bawah pimpinan Abrahah.[25][26] Pendapat paling mashyur merujuk tanggal 12 Rabiul Awal sebagai hari kelahiran Muhammad. Berdasarkan teks hadis, Muhammad menyebut hari Senin sebagai hari kelahirannya. Penulis sirah Sulaiman Al-Manshurfuri dan ahli astronomi Mahmud Basya dalam penelitiannya melacak hari Senin yang dimaksud bertepatan dengan tanggal 9 Rabiul Awal.

Muhammad berasal dari salah satu klan suku Quraisy yakni Bani Hasyim yang mewarisi silsilah terhormat di Mekkah, meskipun tak terpandang karena kekayaannya.[27] Ayahnya, Abdullah meninggal saat Muhammad masih dalam kandungan, enam bulan sebelum kelahiran.[28] Muhammad bayi dibawa tinggal bersama keluarga dusun di pedalaman, mengikuti tradisi perkotaan kala itu untuk memperkuat fisik dan menghindarkan anak dari penyakit perkotaan.[29] Ia diasuh dan disusui oleh Halimah binti Abi Dhuayb di kampung Bani Saad selama dua tahun.[30] Setelah itu, Muhammad kecil dikembalikan untuk diasuh kepada budak Ummu Aiman. Pada usia ke-6, Muhammad kehilangan ibunya, Aminah karena sakit.[30][31] Selama dua tahun berikutnya, kebutuhan Muhammad ditanggung dan dicukupi oleh kakeknya dari keluarga ayah, 'Abd al-Muththalib. Ketika berusia delapan tahun, kakeknya meninggal dan Muhammad berikutnya diasuh oleh pamannya Abu Thalib yang tampil sebagai pemuka Bani Hasyim sepeninggal Abdul Muththalib.</p>

<h2>PENYEBARAN ISLAM</h1>

<p>Sekitar tahun 613 M, tiga tahun setelah Islam disebarkan secara diam-diam, Muhammad mulai melakukan penyebaran Islam secara terbuka kepada masyarakat Mekkah, respons yang ia terima sangat keras dan masif. Ini disebabkan karena ajaran Islam yang dibawa olehnya bertentangan dengan apa yang sudah menjadi budaya dan pola pikir masyarakat Mekkah saat itu. Pemimpin Mekkah Abu Jahal menyatakan bahwa Muhammad adalah orang gila yang akan merusak tatanan hidup orang Mekkah. Akibat penolakan keras yang datang dari masyarakat jahiliyyah di Mekkah dan kekuasaan yang dimiliki oleh para pemimpin Quraisy yang menentangnya, Muhammad dan banyak pemeluk Islam awal disiksa, dianiaya, dihina, disingkirkan, dan dikucilkan dari pergaulan masyarakat Mekkah.

Walau mendapat perlakuan tersebut, ia tetap mendapatkan pengikut dalam jumlah besar. Para pengikutnya ini kemudian menyebarkan ajarannya melalui perdagangan ke negeri Syam, Persia, dan kawasan jazirah Arab. Setelah itu, banyak orang yang penasaran dan tertarik kemudian datang ke Mekkah dan Madinah untuk mendengar langsung dari Muhammad, penampilan dan kepribadian baiknya yang sudah terkenal memudahkannya untuk mendapat simpati dan dukungan dalam jumlah yang lebih besar. Hal ini menjadi semakin mudah ketika Umar bin Khattab dan sejumlah besar tokoh petinggi suku Quraisy lainnya memutuskan untuk memeluk ajaran Islam, meskipun banyak juga yang menjadi antipati mengingat saat itu sentimen kesukuan sangat besar di Mekkah dan Medinah. Tercatat pula Muhammad mendapatkan banyak pengikut dari negeri Farsi (sekarang Iran), salah satu yang tercatat adalah Salman al-Farisi, seorang ilmuwan asal Persia yang kemudian menjadi sahabat Muhammad.

Penyiksaan yang dialami hampir seluruh pemeluk Islam selama periode ini mendorong lahirnya gagasan untuk berhijrah (pindah) ke Habsyah (sekarang Ethiopia). Negus atau raja Habsyah, seorang Kristen yang adil, memperbolehkan orang-orang Islam berhijrah ke negaranya dan melindungi mereka dari tekanan penguasa di Mekkah. Muhammad sendiri, pada tahun 622 hijrah ke Yatsrib, kota yang berjarak sekitar 200 mil (320 km) di sebelah Utara Mekkah.</p>